controller:
  ros__parameters:
    setpoint_r_x: 0.0
    setpoint_r_y: 0.0
    setpoint_r_z: 0.0
    setpoint_v_x: 0.0
    setpoint_v_y: 0.0
    setpoint_v_z: 0.0
    g: 1.62 # [m/s^2] on the moon
    um: 20.0