dynamics:
  ros__parameters:
    r_x0: 2000.0
    r_y0: 1000.0
    r_z0: 4000.0
    v_x0: 0.0
    v_y0: 0.0
    v_z0: 0.0
    g_x: 0.0
    g_y: 0.0
    g_z: 1.62 # [m/s^2] on the moon
    dt: 0.01 #sec